# Generated by Django 5.1.3 on 2024-12-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyect',
            old_name='tittle',
            new_name='title',
        ),
    ]
